# Generated by Django 5.2.14 on 2026-05-06 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('year_level', models.IntegerField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The student (user) this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Record',
                'verbose_name_plural': 'Student Records',
                'ordering': ['full_name'],
            },
        ),
    ]
